---
- name: Creating the directories to containers in /home
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  loop:
    - "/home/{{ username }}/containers/jellyfin/config"        
    - "/home/{{ username }}/containers/jellyfin/cache" 
    - "/home/{{ username }}/containers/jellyfin/media" 
    - "/home/{{ username }}/containers/gitea" 
    - "/home/{{ username }}/containers/immich/library"       

- name: Configure ssh
  block:
    - name: Creates .ssh directory
      ansible.builtin.file:
        path: /home/{{username}}/.ssh
        state: directory

    - name: Creating authorized_keys file
      file:
        path: /home/{{username}}/.ssh/authorized_keys
        state: touch

    - name: Adding ssh_public_key to authorized_keys 
      copy: 
        dest: /home/{{username}}/.ssh/authorized_keys
        content: |
          {{ssh_public_key}}

  when: ssh_public_key|length > 0

