---
- name: Creating the directories to containers in /home
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  loop:
    - "/home/{{ username }}/containers/jellyfin/config"        
    - "/home/{{ username }}/containers/jellyfin/cache" 
    - "/home/{{ username }}/containers/jellyfin/media" 
    - "/home/{{ username }}/containers/gitea" 
    - "/home/{{ username }}/containers/immich/library"       
    - "/home/{{ username }}/containers/prometheus"

- name: Copy prometheus config file in /containers/prometheus
  copy:
    src: /root/ansible/ansible-server-voidlinux/docker/prometheus-config/prometheus.yml
    dest: /home/{{ username }}/containers/prometheus
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: Add ssh public_key
  block:
    - name: Creates .ssh directory
      ansible.builtin.file:
        path: /home/{{username}}/.ssh
        state: directory

    - name: Creating authorized_keys file
      file:
        path: /home/{{username}}/.ssh/authorized_keys
        state: touch

    - name: Adding ssh_public_key to authorized_keys 
      copy: 
        dest: /home/{{username}}/.ssh/authorized_keys
        content: |
          {{ssh_public_key}}
  when: ssh_public_key|length > 0

- name: Change default port from 22 to {{ssh_port}}
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^#Port"
    line: "Port {{ssh_port}}"

- name: Disable SSH password auth
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  when: ssh_password_authentication == "no"

- name: Enable sshd
  service:
    name: sshd
    enabled: yes

- name: Start sshd
  service:
    name: sshd
    state: started

- name: Deny everything and enable UFW
  ufw:
    state: enabled
    policy: deny

- name: UFW - Allow HTTP on ports in 'firewall_allow_ports'
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items: "{{ firewall_allow_ports }}"
